#!/bin/sh

#
# Add an environment variable to /etc/cont-env.d
#

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

usage() {
    echo "usage: $(basename "$0") ENV [VAL]"
}

valid_var_name() {
    case "$1" in
        *[!a-zA-Z0-9_]*|[0-9]*)
            return 1
            ;;
        *)
            return 0
            ;;
    esac
}

if [ $# -eq 0 ] || [ $# -gt 2 ]; then
    usage
    exit 1
fi

NAME="$1"
VAR="${2:-}"

# Determine if we use the "config" or "runtime" directory.
CONT_ENV_DIR=/var/run/cont-env
[ -d "$CONT_ENV_DIR" ] || CONT_ENV_DIR=/etc/cont-env.d

if ! valid_var_name "$NAME"; then
    echo "ERROR: Invalid environment variable name '$NAME'."
    exit 1
fi

echo "$VAR" > "$CONT_ENV_DIR"/"$NAME"

# vim:ft=sh:ts=4:sw=4:et:sts=4
